#!/usr/bin/env bash
# Release script for {{CRATE_NAME}}
# Generated by gh-guard — https://github.com/gh-guard/gh-guard
#
# Usage: scripts/release.sh <version>
# Example: scripts/release.sh 0.1.11
#
# Flow: local checks → release branch → PR → CI → merge → signed tag → CI publish
#
# Supports repos with branch protection: creates a PR for the version bump,
# waits for CI, then merges (with --admin if needed), tags, and releases.
#
# GOTCHAS:
#   - `gh pr checks --watch` has a race condition: returns immediately if checks
#     haven't started yet. This script polls for check existence first.
#   - Tag protection means a wrong tag requires a new version number.
#   - `gh run rerun` uses the original workflow file, not the current one.
set -euo pipefail

VERSION="${1:-}"

# ── Validate arguments ───────────────────────────────────────────
if [[ -z "$VERSION" ]]; then
    echo "Usage: scripts/release.sh <version>"
    echo "Example: scripts/release.sh 0.1.11"
    exit 1
fi

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Version '$VERSION' is not valid semver (expected X.Y.Z)"
    exit 1
fi

# ── Verify signing key ─────────────────────────────────────────
if ! git config user.signingkey &>/dev/null; then
    echo "Error: No signing key configured. Set up GPG or SSH signing:"
    echo "  GPG: git config --global user.signingkey <KEY_ID>"
    echo "  SSH: git config --global gpg.format ssh"
    echo "       git config --global user.signingkey ~/.ssh/id_ed25519.pub"
    exit 1
fi

# ── Verify clean state ──────────────────────────────────────────
if [[ -n "$(git status --porcelain)" ]]; then
    echo "Error: Working tree is not clean. Commit or stash changes first."
    git status --short
    exit 1
fi

BRANCH="$(git branch --show-current)"
if [[ "$BRANCH" != "main" ]]; then
    echo "Error: Must be on 'main' branch (currently on '$BRANCH')"
    exit 1
fi

# Ensure we're up to date
git fetch origin main --quiet
LOCAL_SHA="$(git rev-parse HEAD)"
REMOTE_SHA="$(git rev-parse origin/main)"
if [[ "$LOCAL_SHA" != "$REMOTE_SHA" ]]; then
    echo "Error: Local main ($LOCAL_SHA) differs from origin/main ($REMOTE_SHA)"
    echo "Run 'git pull origin main' first."
    exit 1
fi

echo "==> Releasing {{CRATE_NAME}} v$VERSION"

# ── Detect workspace ────────────────────────────────────────────
IS_WORKSPACE=false
PUBLISHABLE_CRATES=()
if grep -q '^\[workspace\]' Cargo.toml 2>/dev/null; then
    if ! command -v jq &>/dev/null; then
        echo "Error: jq is required for workspace support. Install: brew install jq (macOS) or apt-get install jq (Linux)"
        exit 1
    fi
    IS_WORKSPACE=true
    # Detect publishable workspace members
    while IFS= read -r crate; do
        PUBLISHABLE_CRATES+=("$crate")
    done < <(cargo metadata --no-deps --format-version 1 \
        | jq -r '.packages[] | select(.publish == null or (.publish | length == 0) or (.publish | index("false") | not)) | .name' \
        2>/dev/null || true)
    if [[ ${#PUBLISHABLE_CRATES[@]} -eq 0 ]]; then
        echo "Error: No publishable crates found in workspace"
        exit 1
    fi
    echo "    Workspace detected with ${#PUBLISHABLE_CRATES[@]} publishable crate(s): ${PUBLISHABLE_CRATES[*]}"
fi

# ── Check current version ────────────────────────────────────────
CURRENT="$(sed -nE 's/^version = "([^"]+)"/\1/p' Cargo.toml | head -n1)"
echo "    Current version: $CURRENT"
echo "    New version:     $VERSION"

if [[ "$IS_WORKSPACE" == true ]]; then
    # Verify all publishable members have the same version
    for crate in "${PUBLISHABLE_CRATES[@]}"; do
        CRATE_DIR="$(cargo metadata --no-deps --format-version 1 \
            | jq -r --arg name "$crate" '.packages[] | select(.name == $name) | .manifest_path' \
            | xargs dirname)"
        CRATE_VER="$(sed -nE 's/^version = "([^"]+)"/\1/p' "$CRATE_DIR/Cargo.toml" | head -n1)"
        if [[ "$CRATE_VER" != "$CURRENT" ]]; then
            echo "Error: Crate '$crate' has version $CRATE_VER but root has $CURRENT"
            exit 1
        fi
    done
fi

if [[ "$CURRENT" == "$VERSION" ]]; then
    echo "Error: Cargo.toml already at version $VERSION"
    exit 1
fi

if git tag -l "v$VERSION" | grep -q "v$VERSION"; then
    echo "Error: Tag v$VERSION already exists"
    exit 1
fi

# ── Run local checks ────────────────────────────────────────────
echo "==> Running cargo deny check..."
if command -v cargo-deny &>/dev/null; then
    cargo deny check advisories bans licenses sources
else
    echo "    Warning: cargo-deny not installed, skipping (install: cargo install cargo-deny)"
fi

echo "==> Running tests..."
cargo test --locked --all-features --quiet

echo "==> Running clippy..."
cargo clippy --all-features -- -D warnings 2>&1 | tail -1

echo "==> Dry-run publish..."
cargo publish --dry-run --locked 2>&1 | tail -3

# ── Bump version on a release branch ────────────────────────────
RELEASE_BRANCH="release/v$VERSION"
echo "==> Creating release branch '$RELEASE_BRANCH'..."
git checkout -b "$RELEASE_BRANCH"

echo "==> Bumping Cargo.toml to $VERSION"
sed -i.bak "s/^version = \"$CURRENT\"/version = \"$VERSION\"/" Cargo.toml
rm -f Cargo.toml.bak

if [[ "$IS_WORKSPACE" == true ]]; then
    # Bump version in all publishable workspace members
    for crate in "${PUBLISHABLE_CRATES[@]}"; do
        CRATE_DIR="$(cargo metadata --no-deps --format-version 1 \
            | jq -r --arg name "$crate" '.packages[] | select(.name == $name) | .manifest_path' \
            | xargs dirname)"
        echo "    Bumping $crate ($CRATE_DIR/Cargo.toml)"
        sed -i.bak "s/^version = \"$CURRENT\"/version = \"$VERSION\"/" "$CRATE_DIR/Cargo.toml"
        rm -f "$CRATE_DIR/Cargo.toml.bak"
    done

    # Update inter-crate dependency versions (path deps with version = "=X.Y.Z")
    while IFS= read -r toml; do
        if grep -q "version = \"=$CURRENT\"" "$toml" 2>/dev/null; then
            echo "    Updating inter-crate dep version in $toml"
            sed -i.bak "s/version = \"=$CURRENT\"/version = \"=$VERSION\"/" "$toml"
            rm -f "$toml.bak"
        fi
    done < <(find . -name Cargo.toml -not -path './target/*')
fi

# Update Cargo.lock
if [[ "$IS_WORKSPACE" == true ]]; then
    cargo check --workspace --quiet 2>/dev/null
else
    cargo check --quiet 2>/dev/null
fi

if [[ "$IS_WORKSPACE" == true ]]; then
    # Stage all modified Cargo.toml files
    find . -name Cargo.toml -not -path ./target/\* -exec git add {} +
    git add Cargo.lock
else
    git add Cargo.toml Cargo.lock
fi
git commit -m "Bump version to $VERSION"
git push -u origin "$RELEASE_BRANCH"

# ── Create PR and wait for CI ────────────────────────────────────
echo "==> Creating pull request..."
PR_URL="$(gh pr create \
    --title "Release v$VERSION" \
    --body "Bump version to $VERSION for release." \
    --base main \
    --head "$RELEASE_BRANCH")"
PR_NUMBER="$(echo "$PR_URL" | grep -oE '[0-9]+$')"
echo "    PR #$PR_NUMBER: $PR_URL"

# GOTCHA: gh pr checks --watch returns immediately if checks haven't started.
# Poll until at least one check is registered.
echo "==> Waiting for CI checks to start..."
for i in $(seq 1 30); do
    if gh pr checks "$PR_NUMBER" --json name --jq '.[0].name' &>/dev/null 2>&1; then
        break
    fi
    sleep 2
done

echo "==> Waiting for CI checks to complete..."
if ! gh pr checks "$PR_NUMBER" --watch; then
    echo "Error: CI checks failed on PR #$PR_NUMBER"
    echo "Fix the issues, then re-run this script or merge manually."
    git checkout main
    exit 1
fi

# ── Merge PR ─────────────────────────────────────────────────────
echo "==> Merging PR #$PR_NUMBER..."
if ! gh pr merge "$PR_NUMBER" --squash --delete-branch; then
    echo ""
    echo "    Standard merge failed. This usually means branch protection is blocking."
    echo "    Using --admin bypasses branch protection (required reviews, status checks)."
    read -rp "    Merge with --admin (bypasses branch protection)? [y/N] " ADMIN_CONFIRM
    if [[ "$ADMIN_CONFIRM" =~ ^[Yy]$ ]]; then
        gh pr merge "$PR_NUMBER" --squash --delete-branch --admin
    else
        echo "    Aborting. Fix the issue and merge PR #$PR_NUMBER manually."
        git checkout main
        exit 1
    fi
fi

# ── Update local main ───────────────────────────────────────────
git checkout main
git pull origin main

# ── Tag and push ─────────────────────────────────────────────────
echo "==> Creating signed tag v$VERSION..."
git tag -s "v$VERSION" -m "Release v$VERSION"
git push origin "v$VERSION"

# ── Cleanup ──────────────────────────────────────────────────────
git branch -d "$RELEASE_BRANCH" 2>/dev/null || true

echo ""
echo "Done! Tag v$VERSION pushed."
echo "  - CI will: publish to crates.io, create GitHub Release, attach SLSA provenance."
echo "  - Monitor: gh run watch \$(gh run list --limit 1 --workflow publish.yml --json databaseId -q '.[0].databaseId')"
